# Generated by Django 5.1.3 on 2024-11-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='مشخصه در سایت')),
                ('owner', models.CharField(max_length=100, verbose_name='مدرس')),
                ('subject', models.CharField(max_length=100, verbose_name='موضوع')),
                ('short_description', models.TextField(verbose_name='توضیحات کوتاه ')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_module/static/images', verbose_name='تصویر')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('view', models.IntegerField(blank=True, default=1, null=True, verbose_name='تعداد مشاهده')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
            ],
            options={
                'verbose_name': ('دسته محصولات آموزشی',),
                'verbose_name_plural': 'دسته های محصولات آموزشی',
            },
        ),
    ]
