# Generated by Django 5.1.3 on 2024-12-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_product_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='زمان آموزش'),
        ),
    ]
