# Generated by Django 5.1.3 on 2024-12-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='توضیحات',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='عکس پروفایل',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/profile', verbose_name='عکس پروفایل'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
